services:
  whatifweb:
    image: whatifweb
    container_name: whatifweb
    build:
      context: ../whatif.web
      dockerfile: ${PWD:-.}/Dockerfile
    depends_on:
      - whatifapi

  whatifapi:
    image: whatifapi
    container_name: whatifapi
    build:
      context: ../whatif.api
      dockerfile: ${PWD:-.}/Dockerfile
    # depends_on:
    #   - redis
  
  whatifapi-dapr:
    container_name: whatifapi-dapr
    image: "daprio/daprd:edge"
    network_mode: "service:whatifapi"
    depends_on:
      - whatifapi

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"

# Components
  #Pub-Sub & State
  # redis:
  #   container_name: redis
  #   image: redis:alpine

  # Observability
  # zipkin:
  #   container_name: zipkin
  #   image: openzipkin/zipkin-slim
# Components