
POST http://localhost:3602/v1.0/invoke/whatifapi/method/user HTTP/1.1
content-type: application/json

{
    "email": "filon.fisteku@gmail.com",
    "password": "123456",
    "firstName": "filon",
    "lastName": "fisteku"
}

###

# @name login
POST http://localhost:3602/v1.0/invoke/whatifapi/method/user/login HTTP/1.1
content-type: application/json

{
    "email": "filon.fisteku@gmail.com",
    "password": "123456"
}
###

@authToken = {{login.response.body.token}}

GET http://localhost:3602/v1.0/invoke/whatifapi/method/user HTTP/1.1
Authorization: Bearer {{authToken}}
###
