name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: [source/whatif.api/**]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag whatifapie:$(date +%s) --file source/whatif.api/Dockerfile source/whatif.api
