name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: [source/whatif.web/**]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag whatifweb:$(date +%s) --file source/whatif.web/Dockerfile source/whatif.web
